content: "New WOKO room!"
receiver_email: "pass" # email to send to 
sender_email: "pass" # email to send from 
password: "pass" # password of the sender_email email 
keyword: "Zürich" # Choose between Zürich and Winterthur
timer: 120 # in s./ interval to update request
